[package]
name = "rust_glium_opengl_test"
version = "0.1.0"
authors = ["Michal B. <michal2229@gmail.com>"]

[dependencies]
glium = "*"
rand = "0.3"
genmesh = "0.4"
obj = { version = "0.5", features = ["usegenmesh"] }
